# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.unary_unary(
                '/tictactoeserver.Game/connect',
                request_serializer=messages__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=messages__pb2.PlayerResponse.FromString,
                )
        self.update = channel.stream_stream(
                '/tictactoeserver.Game/update',
                request_serializer=messages__pb2.UpdateRequest.SerializeToString,
                response_deserializer=messages__pb2.UpdateResponce.FromString,
                )
        self.makeMove = channel.stream_stream(
                '/tictactoeserver.Game/makeMove',
                request_serializer=messages__pb2.MoveRequest.SerializeToString,
                response_deserializer=messages__pb2.MoveResponse.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def makeMove(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.unary_unary_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=messages__pb2.ConnectionRequest.FromString,
                    response_serializer=messages__pb2.PlayerResponse.SerializeToString,
            ),
            'update': grpc.stream_stream_rpc_method_handler(
                    servicer.update,
                    request_deserializer=messages__pb2.UpdateRequest.FromString,
                    response_serializer=messages__pb2.UpdateResponce.SerializeToString,
            ),
            'makeMove': grpc.stream_stream_rpc_method_handler(
                    servicer.makeMove,
                    request_deserializer=messages__pb2.MoveRequest.FromString,
                    response_serializer=messages__pb2.MoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tictactoeserver.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tictactoeserver.Game/connect',
            messages__pb2.ConnectionRequest.SerializeToString,
            messages__pb2.PlayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tictactoeserver.Game/update',
            messages__pb2.UpdateRequest.SerializeToString,
            messages__pb2.UpdateResponce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def makeMove(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tictactoeserver.Game/makeMove',
            messages__pb2.MoveRequest.SerializeToString,
            messages__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
